name: Security Scan

on:
  pull_request:
  schedule:
    # every day at 00:00, on the default branch  (master)
    - cron: '0 0 * * *'

permissions:
  contents: read
  id-token: write

jobs:
  security-scan:
    uses: IoFinnet/reusable-workflows/.github/workflows/security-scan.yaml@main
